language: go

# vanity url support
go_import_path: gnorm.org/gnorm

# prevent double test runs for PRs
branches:
  only:
    - "master"

# In theory, older versions would probably work fine, but since this isn't a 
# library, I'm not going to worry about older versions for now.
go:
  - tip
  - "1.11"
  - "1.10"
# https://github.com/go-sql-driver/mysql/issues/1040
# go-sql-driver/mysql : Go 1.9 is not supported
#  - "1.9"

# don't call go get ./... because this hides when deps are
# not packaged into the vendor directory.
install: true

# don't call go test -v because we want to be able to only show t.Log output when
# a test fails
script: go test -race ./...

