language: go

# vanity url support
go_import_path: gnorm.org/gnorm

# prevent double test runs for PRs
branches:
  only:
    - "master"

# In theory, older versions would probably work fine, but since this isn't a 
# library, I'm not going to worry about older versions for now.
go:
  - tip
  - "1.15"
  - "1.14"
  - "1.13"
  - "1.12"

env:
  - GO111MODULE=on

# don't call go test -v because we want to be able to only show t.Log output when
# a test fails
script: go test -race ./...

