# This is the gnorm.toml that generates the DB access code for mysql databases.
# Its output is contained in the database/drivers/mysql/db driectory.  It
# assumes you have a mysql instance running locally, with the root user given a
# password of gnorm.

ConnStr = "root:gnorm@tcp/"

DBType = "mysql"

Schemas = ["information_schema"]

NameConversion = "{{. | pascal}}"

IncludeTables = ["TABLES", "COLUMNS", "STATISTICS"]

PostRun = ["goimports", "-w", "$GNORMFILE"]


[TablePaths]
"gnorm/{{toLower .Table}}/{{toLower .Table}}.go" = "templates/table.gotmpl"

[SchemaPaths]
"gnorm/fields.go" = "templates/schema.gotmpl"


[TypeMap]
 "datetime" = "time.Time"
 "longtext" = "string"
 "boolean" = "bool"
 "varchar" = "string"
 "bigint" = "int64"
 "int" = "int"

[NullableTypeMap]
"datetime" = "mysql.NullTime"
"longtext" = "sql.NullString"
"boolean" = "sql.NullBool"
"varchar" = "sql.NullString"
"int" = "sql.NullInt64"
"bigint" = "sql.NullInt64"
